# Generated by Django 3.0.6 on 2020-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_img',
            field=models.ImageField(blank=True, upload_to='users'),
        ),
    ]
