# Generated by Django 3.0.6 on 2020-06-13 17:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_display_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='hi', editable=False, populate_from=['first_name', 'last_name']),
            preserve_default=False,
        ),
    ]
