# Generated by Django 3.0.6 on 2020-06-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
