# Generated by Django 3.0.6 on 2020-06-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200613_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
