# Generated by Django 3.0.6 on 2020-06-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='from_person',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='to_person',
            new_name='to_user',
        ),
    ]
