# Generated by Django 3.0.6 on 2020-05-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0003_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-updated_date']},
        ),
        migrations.AddField(
            model_name='answer',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
