# Generated by Django 3.0.6 on 2020-06-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0007_question_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
