# Generated by Django 3.0.6 on 2020-06-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0008_auto_20200610_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.TextField(),
        ),
    ]
