# Generated by Django 3.0.6 on 2020-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0009_auto_20200611_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pin_answer',
            field=models.BooleanField(default=False),
        ),
    ]
