# Generated by Django 3.0.6 on 2020-06-24 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qnA', '0011_remove_question_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_question', to='qnA.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_question_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
