# Generated by Django 3.0.6 on 2020-05-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qnA', '0006_auto_20200527_2352'),
        ('comments', '0002_auto_20200529_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomment',
            name='ans',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='qnA.Answer'),
        ),
    ]
