# Generated by Django 3.0.6 on 2020-05-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200529_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomment',
            name='ans',
        ),
    ]
