# Generated by Django 3.0.6 on 2020-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_mycomment_ans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycomment',
            options={},
        ),
        migrations.AddField(
            model_name='mycomment',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='mycomment',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='mycomment',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
