# Generated by Django 3.0.6 on 2020-06-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
