# Generated by Django 3.0.6 on 2020-06-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200627_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_followed_ans',
            new_name='is_followed_question',
        ),
    ]
