# Generated by Django 3.0.6 on 2020-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200620_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question_slug',
            field=models.SlugField(default='hello-world'),
            preserve_default=False,
        ),
    ]
